package com.dishant.jewelcore.pricing.service;

import com.dishant.jewelcore.common.exception.ResourceNotFoundException;
import com.dishant.jewelcore.inventory.jewellery.entity.Jewellery;
import com.dishant.jewelcore.inventory.stock.entity.InventoryItem;
import com.dishant.jewelcore.inventory.stock.repository.InventoryItemRepository;
import com.dishant.jewelcore.masterdata.category.entity.Category;
import com.dishant.jewelcore.masterdata.metal.entity.Metal;
import com.dishant.jewelcore.masterdata.metalprice.entity.DailyMetalPrice;
import com.dishant.jewelcore.masterdata.metalprice.repository.DailyMetalPriceRepository;
import com.dishant.jewelcore.masterdata.purity.entity.Purity;
import com.dishant.jewelcore.pricing.dto.PriceCalculationRequest;
import com.dishant.jewelcore.pricing.dto.PriceCalculationResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class PricingServiceTest {

    @Mock
    private InventoryItemRepository inventoryItemRepository;

    @Mock
    private DailyMetalPriceRepository dailyMetalPriceRepository;

    private PricingService pricingService;

    private InventoryItem inventoryItem;

    private DailyMetalPrice dailyMetalPrice;

    private final LocalDate priceDate =
            LocalDate.of(2026, 8, 13);

    @BeforeEach
    void setUp() {

        pricingService = new PricingService(
                inventoryItemRepository,
                dailyMetalPriceRepository
        );

        /*
         * Metal is mocked because its database ID is generated
         * by JPA and is otherwise null in a unit test.
         */
        Metal gold = mock(Metal.class);

        lenient()
                .when(gold.getId())
                .thenReturn(1L);

        lenient()
                .when(gold.getName())
                .thenReturn("Gold");

        lenient()
                .when(gold.getCode())
                .thenReturn("GOLD");

        Purity purity = new Purity(
                "22 Karat",
                "22K",
                new BigDecimal("91.60")
        );

        Category category = new Category(
                "Rings",
                "RING"
        );

        Jewellery jewellery = new Jewellery(
                "RING-001",
                "Classic Gold Ring",
                "22K gold ring",
                category,
                gold,
                purity,
                new BigDecimal("5.000"),
                new BigDecimal("0.000"),
                new BigDecimal("5.000"),
                new BigDecimal("2500.00")
        );

        inventoryItem = spy(new InventoryItem(
                "ITEM-001",
                jewellery,
                new BigDecimal("5.000"),
                new BigDecimal("0.000"),
                new BigDecimal("5.000"),
                new BigDecimal("30000.00"),
                "SHOWROOM-A"
        ));

        /*
         * InventoryItem ID is normally generated by the database.
         */
        lenient()
                .when(inventoryItem.getId())
                .thenReturn(1L);

        dailyMetalPrice = new DailyMetalPrice(
                gold,
                priceDate,
                new BigDecimal("7250.00")
        );
    }

    @Test
    void shouldCalculatePriceSuccessfully() {

        PriceCalculationRequest request =
                new PriceCalculationRequest(
                        1L,
                        priceDate
                );

        when(inventoryItemRepository.findById(1L))
                .thenReturn(Optional.of(inventoryItem));

        when(dailyMetalPriceRepository.findByMetalIdAndPriceDate(
                1L,
                priceDate
        ))
                .thenReturn(Optional.of(dailyMetalPrice));

        PriceCalculationResponse result =
                pricingService.calculatePrice(request);

        assertThat(result).isNotNull();

        assertThat(result.inventoryItemId())
                .isEqualTo(1L);

        assertThat(result.itemCode())
                .isEqualTo("ITEM-001");

        assertThat(result.jewelleryName())
                .isEqualTo("Classic Gold Ring");

        assertThat(result.metalCode())
                .isEqualTo("GOLD");

        assertThat(result.purityCode())
                .isEqualTo("22K");

        assertThat(result.purityPercentage())
                .isEqualByComparingTo("91.60");

        assertThat(result.metalRatePerGram())
                .isEqualByComparingTo("7250.00");

        assertThat(result.netWeight())
                .isEqualByComparingTo("5.000");

        /*
         * 7250 × 91.60% = 6641.00
         */
        assertThat(result.pureMetalRatePerGram())
                .isEqualByComparingTo("6641.00");

        /*
         * 5.000 × 6641.00 = 33205.00
         */
        assertThat(result.metalValue())
                .isEqualByComparingTo("33205.00");

        assertThat(result.makingCharge())
                .isEqualByComparingTo("2500.00");

        /*
         * 33205.00 + 2500.00 = 35705.00
         */
        assertThat(result.finalPrice())
                .isEqualByComparingTo("35705.00");
    }

    @Test
    void shouldRejectWhenInventoryItemDoesNotExist() {

        PriceCalculationRequest request =
                new PriceCalculationRequest(
                        99L,
                        priceDate
                );

        when(inventoryItemRepository.findById(99L))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() ->
                pricingService.calculatePrice(request)
        )
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage(
                        "Inventory item not found with id: 99"
                );
    }

    @Test
    void shouldRejectWhenMetalPriceDoesNotExist() {

        PriceCalculationRequest request =
                new PriceCalculationRequest(
                        1L,
                        priceDate
                );

        when(inventoryItemRepository.findById(1L))
                .thenReturn(Optional.of(inventoryItem));

        when(dailyMetalPriceRepository.findByMetalIdAndPriceDate(
                1L,
                priceDate
        ))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() ->
                pricingService.calculatePrice(request)
        )
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage(
                        "Metal price not found for metal 1 on "
                                + priceDate
                );
    }

    @Test
    void shouldCalculatePriceUsingPurityPercentage() {

        PriceCalculationRequest request =
                new PriceCalculationRequest(
                        1L,
                        priceDate
                );

        when(inventoryItemRepository.findById(1L))
                .thenReturn(Optional.of(inventoryItem));

        when(dailyMetalPriceRepository.findByMetalIdAndPriceDate(
                1L,
                priceDate
        ))
                .thenReturn(Optional.of(dailyMetalPrice));

        PriceCalculationResponse result =
                pricingService.calculatePrice(request);

        /*
         * 7250 × 91.60% = 6641.00
         */
        assertThat(result.pureMetalRatePerGram())
                .isEqualByComparingTo("6641.00");
    }

    @Test
    void shouldRoundFinalPriceToTwoDecimalPlaces() {

        Metal gold = mock(Metal.class);

        when(gold.getId())
                .thenReturn(1L);

        when(gold.getName())
                .thenReturn("Gold");

        when(gold.getCode())
                .thenReturn("GOLD");

        Purity purity = new Purity(
                "18 Karat",
                "18K",
                new BigDecimal("75.00")
        );

        Category category = new Category(
                "Rings",
                "RING"
        );

        Jewellery jewellery = new Jewellery(
                "RING-002",
                "18K Ring",
                null,
                category,
                gold,
                purity,
                new BigDecimal("2.345"),
                new BigDecimal("0.000"),
                new BigDecimal("2.345"),
                new BigDecimal("1234.56")
        );

        InventoryItem item = new InventoryItem(
                "ITEM-002",
                jewellery,
                new BigDecimal("2.345"),
                new BigDecimal("0.000"),
                new BigDecimal("2.345"),
                new BigDecimal("10000.00"),
                "SHOWROOM-A"
        );

        DailyMetalPrice price = new DailyMetalPrice(
                gold,
                priceDate,
                new BigDecimal("7250.00")
        );

        when(inventoryItemRepository.findById(2L))
                .thenReturn(Optional.of(item));

        when(dailyMetalPriceRepository.findByMetalIdAndPriceDate(
                1L,
                priceDate
        ))
                .thenReturn(Optional.of(price));

        PriceCalculationResponse result =
                pricingService.calculatePrice(
                        new PriceCalculationRequest(
                                2L,
                                priceDate
                        )
                );

        /*
         * 7250 × 75% = 5437.50
         */
        assertThat(result.pureMetalRatePerGram())
                .isEqualByComparingTo("5437.50");

        /*
         * 2.345 × 5437.50 = 12750.9375
         * Rounded to 2 decimals = 12750.94
         */
        assertThat(result.metalValue())
                .isEqualByComparingTo("12750.94");

        /*
         * 12750.94 + 1234.56 = 13985.50
         */
        assertThat(result.finalPrice())
                .isEqualByComparingTo("13985.50");
    }
}