spring:
  application:
    name: jewelcore

  datasource:
    url: jdbc:mysql://localhost:3306/jewelcore
    username: root
    password: Dish@7890

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080